[package]
name = "fluid_sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.3"
nalgebra = "0.32.3"
rand = "0.8.5"
rayon = "1.8.0"
rstar = "0.11.0"

[profile.release]
debug = true
